theme = "tokyonight_moon"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
cursorline = true
color-modes = true
auto-pairs = true
true-color = true
end-of-line-diagnostics = "error"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "warning"

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.lsp]
# display-inlay-hints = true
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = ["file-type"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[keys.normal]
S-h = [
    ":buffer-previous"
]
S-l = [
    ":buffer-next"
]

[keys.normal."space"]
g = [
    ":write-all", 
    ":new", 
    ":insert-output lazygit", 
    ":buffer-close!", 
    ":redraw", 
    ":reload-all"
]
w = { c = ":buffer-close"}

